/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JuanCarlosPuerto' at '17/09/16 8:48 PM' with Gradle 2.14.1
 *
 * @author JuanCarlosPuerto, @date 17/09/16 8:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
